### ISSUE TITLE
Applying datapacks to multiple world folders

### ISSUE THREAD

**Issue by nhasdarjian** [lichenaut/DatapackLoader#5]
DatapackLoader is very effective at modifying and maintaining datapacks for `level.dat` in `/world`.

On my server, I use the MyWorlds plugin to manage custom dimensions.
As far as I have seen, DatapackLoader only looks at `/world` on server startup.

As a result, the datapacks applied on a given custom world are equivalent to
the datapacks enabled on the default world at the time the custom world was created.

To propagate datapack changes to custom worlds, I propose a simple solution:

Add a list of directories containing `level.dat` files in the generated `config.yml`.
This could look like:
```
world-directories:
  - world
  - world_creative
  - world_vanilla_skyblock
```
Users can define custom worlds to let the plugin manage,
and the plugin will treat the `level.dat` files in each folder
the same way that it does `level.dat` in `/world` and keep
it consistent with `sourceList.txt`.

If you wanted to expand on this, you could add extra options for granular control.
This could look like a `worlds.yml` file with the contents:
```
world:
    sync-all: true
    exceptions:
        - creative-datapack
        - vanilla-skyblock-datapack
world_creative:
    sync-all: true
    exceptions:
        - vanilla-skyblock-datapack
world_vanilla_skyblock:
    sync-all: false
    exceptions:
        - vanilla-skyblock-datapack
```
When `sync-all` is true, then DatapackLoader will sync
that world's `level.dat` with the contents of `sourceList.txt`,
excluding any datapack files listed in `exceptions`.

When `sync-all` is false, then DatapackLoader will only sync
that world's `level.dat` with the files listed in `exceptions`.

Thanks for your time in reviewing my suggestion.
